#!/bin/sh

while read oldrev newrev refname

echo "Publishing update: $GIT_DIR ==> $GIT_WORK_TREE"

do

    branch=$(git rev-parse --symbolic --abbrev-ref $refname)

    echo "Publishing branch: $branch"

done

## For app-video-web-legacy

export REPO=$(basename "$PWD")
export GIT_DIR=/var/www/repos/$REPO
export GIT_WORK_TREE=/var/www/sites/${REPO%.git}

git checkout -f $branch

#sami update config/sami.php
#apidoc generate

# Can't get sami/sami to install as a package w/ our custom Laravel 4.2.18 branch..
unset GIT_DIR && unset GIT_WORK_TREE
mkdir /var/www/packages/
git clone git@github.com:FriendsOfPHP/sami.git /var/www/packages/sami
